updating document
openinfradev/decapod-docs pull request #4
Opened 2021-08-10 04:30 UTC by ktkfree

일단, decapod deploying 에 대한 부분을 현행화 하였습니다.

검토 부탁 드립니다.

2021-08-10 07:55 UTC, Jaesang requested changes

2021-08-10 07:55 UTC, Jaesang commented on docs/getting-started/deploying.md
> +    -p argo_password="password" \
그냥 password를 입력하기로 되어있어,  위에서 확인한 값을 사용하라는 언급이 있어야할 것 같습니다.

2021-08-10 07:55 UTC, Jaesang commented on docs/getting-started/deploying.md
> +    -p argo_server="argo-cd-argocd-server.argo.svc:80" \
마지막 \는  빼야할 것 같습니다.

2021-08-10 07:55 UTC, Jaesang commented on docs/getting-started/deploying.md
> +  argo list -n argo # 생성된 workflow가 완료될 때까지 기다린다.
위에는 argo ls를 사용하고 있어서 두개를 같은 명령어로 맞추는게 나을거 같습니다.

2021-08-10 08:18 UTC, ktkfree commented on docs/getting-started/deploying.md
> +  argo list -n argo # 생성된 workflow가 완료될 때까지 기다린다.
argo ls 가 deprecate 된것 같더라고요. list 로 변경하겠습니다.

2021-08-10 08:20 UTC, ktkfree commented on docs/getting-started/deploying.md
> +    -p argo_password="password" \
변경했습니다

2021-08-10 08:20 UTC, ktkfree commented on docs/getting-started/deploying.md
> +    -p argo_server="argo-cd-argocd-server.argo.svc:80" \
변경했습니다

2021-08-10 08:28 UTC, ktkfree commented
LMA 설치를 위해서는 메뉴얼의 내용뿐만아니라 ( 맞는 step 인지는 모르겠어서 추가하지 않았습니다. ) 아래의 내용도 필요한것 같아요.
아래 스텝을 개발 중으로 알고 있는데, 아래 내용 중 메뉴얼화 해야 할 만한 내용이 있다면 코멘트 바랍니다.

taco-storage 에러
 . pv와 storageClass 를 taco-storage로 수동 추가

cluster name
 . argo-cd cluster 이름을 사이트명과 동일하게 UI에서 변경 ( 예. hanu-reference로 )

namespace 생성
 . kubectl create ns lma

노드 label
 . kubectl label nodes kind-control-plane taco-lma=enabled

2021-08-10 13:50 UTC, Jaesang commented
> LMA 설치를 위해서는 메뉴얼의 내용뿐만아니라 ( 맞는 step 인지는 모르겠어서 추가하지 않았습니다. ) 아래의 내용도 필요한것 같아요.
> 아래 스텝을 개발 중으로 알고 있는데, 아래 내용 중 메뉴얼화 해야 할 만한 내용이 있다면 코멘트 바랍니다.
> 
> taco-storage 에러
> . pv와 storageClass 를 taco-storage로 수동 추가
> 
> cluster name
> . argo-cd cluster 이름을 사이트명과 동일하게 UI에서 변경 ( 예. hanu-reference로 )
> 
> namespace 생성
> . kubectl create ns lma
> 
> 노드 label
> . kubectl label nodes kind-control-plane taco-lma=enabled

이 부분은 Decapod보다는 LMA 특화된 부분이라 이 문서에서 다룰 필요는 없지 않을까합니다

2021-08-10 13:51 UTC, Jaesang approved these changes

2021-08-11 01:02 UTC, robertchoi80 commented on docs/getting-started/deploying.md
>      -p repository_url="https://github.com/openinfradev/decapod-manifests" # decapod-manifests repository 주소
openinfradev가 아닌 "YOUR_REPOSITORY_NAME" 으로 바뀌어야할 것 같습니다.

2021-08-18 02:22 UTC, Jaesang commented on docs/getting-started/deploying.md
>      -p repository_url="https://github.com/openinfradev/decapod-manifests" # decapod-manifests repository 주소
@ktkfree 업데이트해주세요~

2021-08-18 04:29 UTC, ktkfree commented on docs/getting-started/deploying.md
>      -p repository_url="https://github.com/openinfradev/decapod-manifests" # decapod-manifests repository 주소
@robertchoi80 @Jaesang 업데이트는 했는데, github 인증방식이 8/13에 변경되면서 push 를 못하고 있었어요. 이부분 확인후 push 하도록 하겠습니다. 감사합니다.

2021-08-18 07:56 UTC, ktkfree commented on docs/getting-started/deploying.md
>      -p repository_url="https://github.com/openinfradev/decapod-manifests" # decapod-manifests repository 주소
변경했습니다~

2021-08-18 15:58 UTC, merged

2021-08-19 08:41 UTC, robertchoi80 commented on docs/getting-started/deploying.md
>      -p repository_url="https://github.com/openinfradev/decapod-manifests" # decapod-manifests repository 주소
앗! 이거 엉뚱한 부분이 수정되었는데요?  site_name 이 아니라 repository_url 의 'openinfradev' 부분을 말씀드린 것입니다.

2021-08-19 09:43 UTC, ktkfree commented on docs/getting-started/deploying.md
>      -p repository_url="https://github.com/openinfradev/decapod-manifests" # decapod-manifests repository 주소
앗 수정부분이 저걸로 떠서 무의식적으로 site name을 수정해버렸네요.
수정 pr 올릴게요. 감사합니다